language: node_js

node_js:
  - '8'

script:
  - yarn test
  - yarn build

after_script:
  - node now-travis.js

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: aEE3FILmPONrxBuo67BMy/TJaBaHCvdf52RrK3UiNI9hpTZhPZBAXen2WX/4zMST8yoaVmI2n394Mb/hP2aQ+biFLHF+6135Pf6AvVObYWkSzp0y4XDWDL4TJgvAggNFxPp6n80d1IAzbw5xsM+n/DKn2JnDRaxCPhT5mz39qh1X/ZGn4FKmiObRZSQFYqP84HWYuKBxzrOVAIm6ZLi9OFpvXlMPo8ezLQGDle0S5DMO8P6pDlPEXelG1Wil5xy5cQzW3Vf4OBxpZSEatgOdASXR0GtBveGVUpFcqc7KS3BncsQGr+SqtlIRPYgBHdlwBTfYtXhK0Q8s1GIms3eGd+iy4JzTO/MqXh9E6ONjp/gYSiFP/2/ixZJwykfgSWBH3xyZGjpMZE9O/SxGEYj0aCmBxeKgXM0iqA/QUq73LE4MlOQS/UUtteSJ0nTP1kzyHHXrxU5CBab9ZPM4ZJuTYev7CH1s2l1fuCt1OUQ2OmuPZ1QbFuYMYmAaCP0njH/uZiC3mjKIMzrept89B1eyFRthWgmjPbtdvdMpEbXigqjAGlQnyGx1lV8jxQre0+4jfSy10+KZNqpv2+oNT1bogHuZv+cODEvTh1ClbVk2r8oKZQIcabDfrn+Islq8rTJTdEacbxNgsBhJiKryhonXSIEFpIDuX/4VmrABBoSJ2NQ=
env:
  global:
    secure: iQjo4YArnivehh/lOCBVy54zvsGWSO5AV2qmqROLE4oSo6gAvR7S5vx7VBUi3vjvNoj21j98DXqXc7ueoHN3PfKaRgxOBB2uTMJrHcFpp9/w4yB3j++fjO+6Fwox8oJapVGaOh/NsyVQzzsw6YQamEKNKgJLGRTcMt2DwrdBC/DfMMNOVLJnBRbetE37FUlt85q+yDUzr9Ojw/iOu2F9fGz2PQSJptwYbNUTV9+ZwoGUpGbzs1pW5U1sOJEc5MO0xtZyvq2kI5uh+Eg7Qw9N9YNW13fo3UwIVLJN2Qk3lz2SzCGrjO955b1fg+TLUwGfOjiMGzD9rY9WubK8tfzhwKey1VSzeVS5sbqsWsSWZsTbeTYcpdI1hWCxtSJAorGa3xOMGlBtKxP0bjw62nfC4mrxzr8W9LxbKmMBSmPR4JgoEiiq5ATqGMPpREA1HJSeOT1mTlkvbS2XhJwpOwCoVrIuJYi9L4xhPMb+sDf9YyjcxWuYoo4TtYVfrKbjGou2ejZGByI3QxGmRDznKOdraBioTCCQIB53LcGMkvU9JKAOUa0yGj7rgoTd9CpmiD8Cc5XKHIazvo1kzQBTi1fC6zzHFZxawyqX1joVwGuYjZ7mDH6QffKI8fqfvt0AwRoeKgANbtZDvP1r3WuccjwKAOKnZ9IOeK8/Lf8TZnniN3o=
